# Generated by Django 3.2.5 on 2021-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_display_notebook_display_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='display',
            new_name='display_type',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='reslution',
            new_name='resolution',
        ),
    ]
