# Generated by Django 3.2.5 on 2021-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210716_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
